topics = [
  {verse: 'water droplet', verse_id: ''},
  {verse: 'silver pickaxe', verse_id: ''},
  {verse: 'shirt', verse_id: ''},
  {verse: 'newspaper', verse_id: ''},
  {verse: 'silver 🏠', verse_id: ''},
  {verse: 'silver map', verse_id: ''},
  {verse: 'clock', verse_id: ''},
  {verse: 'music notes', verse_id: ''},
  {verse: 'video camera', verse_id: ''},
  {verse: 'burger', verse_id: ''},
  {verse: 'book', verse_id: ''},
  {verse: 'tv', verse_id: ''},
  {verse: 'plane', verse_id: ''},
  {verse: 'chess, poker', verse_id: ''},
  {verse: 'baby', verse_id: ''},
  {verse: '🐕', verse_id: ''},
  {verse: 'arrow up to right', verse_id: ''},
  {verse: 'laughing masks', verse_id: ''},
  {verse: 'book with lightbulb', verse_id: ''},
  {verse: '3x3 grid of dots', verse_id: ''},
  {verse: 'sphere with www', verse_id: ''},
  {verse: 'PS4 controller', verse_id: ''},
  {verse: 'VR headset', verse_id: ''},
  {verse: 'mobile phone', verse_id: ''},
  {verse: 'shield with a lock on it', verse_id: ''},
  {verse: 'car with sensors', verse_id: ''},
  {verse: 'microphone with headphones', verse_id: ''},
  {verse: 'small plant growing', verse_id: ''},
  {verse: 'kids throwing a ball', verse_id: ''},
  {verse: '🏫', verse_id: ''},
  {verse: '3 people with arms around each other', verse_id: ''},
  {verse: 'parents with children', verse_id: ''},
  {verse: 'bronze pickaxe', verse_id: ''},
  {verse: 'bronze 🏠', verse_id: ''},
  {verse: 'bronze trophy', verse_id: ''},
  {verse: 'green club (cards)', verse_id: ''},
  {verse: 'cybertruck', verse_id: ''},
  {verse: 'christmas tree', verse_id: ''},
  {verse: 'small printed photo', verse_id: ''},
  {verse: 'beach', verse_id: ''},
  {verse: 'hiking poles', verse_id: ''},
  {verse: '👽', verse_id: ''},
  {verse: 'arrows in a circle', verse_id: ''},
  {verse: '🌟', verse_id: ''},
  {verse: 'dots around word habit', verse_id: ''},
  {verse: 'target', verse_id: ''},
  {verse: 'hand holding ❤️', verse_id: ''},
  {verse: 'a fish near a hook', verse_id: ''},
  {verse: 'Google translate icon', verse_id: ''},
  {verse: 'heart on a laptop', verse_id: ''},
  {verse: 'lightning above person's head', verse_id: ''},
  {verse: '💡 with a brain inside', verse_id: ''},
  {verse: 'superman icon', verse_id: ''},
  {verse: 'smiling face', verse_id: ''},
  {verse: 'Google AdWords', verse_id: ''},
  {verse: '🌟 with name Tom Cruise', verse_id: ''},
  {verse: 'Paper with 401k at the top', verse_id: ''},
  {verse: 'male and female symbols', verse_id: ''},
  {verse: '💰 dropped in hands', verse_id: ''},
  {verse: 'Cloud', verse_id: ''},
  {verse: 'gold map', verse_id: ''},
  {verse: 'car', verse_id: ''},
  {verse: 'tree near bench', verse_id: ''},
  {verse: 'rocketship', verse_id: ''},
  {verse: 'cat', verse_id: ''},
  {verse: 'person with cane', verse_id: ''},
  {verse: 'weight', verse_id: ''},
  {verse: 'beer', verse_id: ''},
  {verse: 'Google', verse_id: ''},
  {verse: 'Tent', verse_id: ''},
  {verse: 'Ice cream cone', verse_id: ''},
  {verse: 'Dress', verse_id: ''},
  {verse: 'Four leaf clover', verse_id: ''},
  {verse: 'Bed', verse_id: ''},
  {verse: 'Two wrenches', verse_id: ''},
  {verse: 'canvas and paintbrush', verse_id: ''},
  {verse: 'Playing cards', verse_id: ''},
  {verse: 'Tree', verse_id: ''},
  {verse: 'Swimming', verse_id: ''},
  {verse: 'i icon', verse_id: ''},
  {verse: 'thumbs down', verse_id: ''},
  {verse: 'Violin', verse_id: ''},
  {verse: 'History channel H', verse_id: ''},
];
