topics = [
  {verse: 'water droplet', verse_id: '(Current situation)'},
  {verse: 'silver pickaxe', verse_id: '(Job / Work)'},
  {verse: 'shirt', verse_id: '(Clothes)'},
  {verse: 'newspaper', verse_id: '(News)'},
  {verse: 'silver 🏠', verse_id: '(Where they are living)'},
  {verse: 'silver map', verse_id: '(Not too distant future)'},
  {verse: 'clock', verse_id: '(Free time)'},
  {verse: 'music notes', verse_id: '(Music)'},
  {verse: 'video camera', verse_id: '(Movies)'},
  {verse: 'burger', verse_id: '(Food)'},
  {verse: 'book', verse_id: '(Books)'},
  {verse: 'tv', verse_id: '(TV)'},
  {verse: 'plane', verse_id: '(Travel)'},
  {verse: 'chess, poker, Dark Souls, GC2', verse_id: '(Hobbies)'},
  {verse: 'baby', verse_id: '(Children)'},
  {verse: '🐕', verse_id: '(Pets)'},
  {verse: 'arrow up to right', verse_id: '(Current trends)'},
  {verse: 'laughing masks', verse_id: '(Comedy / Humor)'},
  {verse: 'book with lightbulb', verse_id: '(Learning / Studies)'},
  {verse: '3x3 grid of dots', verse_id: '(Apps)'},
  {verse: 'sphere with www', verse_id: '(Internet)'},
  {verse: 'PS4 controller', verse_id: '(Games)'},
  {verse: 'VR headset', verse_id: '(Virtual reality)'},
  {verse: 'mobile phone', verse_id: '(Phones)'},
  {verse: 'shield with a lock on it', verse_id: '(Privacy)'},
  {verse: 'car with sensors', verse_id: '(Self-driving cars)'},
  {verse: 'microphone with headphones', verse_id: '(Podcasts)'},
  {verse: 'small plant growing', verse_id: '(Where they grew up)'},
  {verse: 'kids throwing a ball', verse_id: '(Things they were into)'},
  {verse: '🏫', verse_id: '(School)'},
  {verse: '3 people with arms around each other', verse_id: '(Friends)'},
  {verse: 'parents with children', verse_id: '(Family)'},
  {verse: 'bronze pickaxe', verse_id: '(Previous jobs)'},
  {verse: 'bronze 🏠', verse_id: '(Where they have lived)'},
  {verse: 'bronze trophy', verse_id: '(Accomplishments)'},
  {verse: 'green club', verse_id: '(Clubs)'},
  {verse: 'cybertruck', verse_id: '(Cars)'},
  {verse: 'christmas tree', verse_id: '(Holidays)'},
  {verse: 'small printed photo', verse_id: '(Photography)'},
  {verse: 'beach', verse_id: '(The beach)'},
  {verse: 'hiking poles', verse_id: '(Hiking)'},
  {verse: '👽', verse_id: '(Aliens)'},
  {verse: 'arrows in a circle', verse_id: '(Change)'},
  {verse: '🌟', verse_id: '(Talents and Skills)'},
  {verse: 'dots around word habit', verse_id: '(Habits)'},
  {verse: 'target', verse_id: '(Goals)'},
  {verse: 'hand holding ❤️', verse_id: '(Charity / Volunteering)'},
  {verse: 'a fish near a hook', verse_id: '(Fishing)'},
  {verse: 'Google translate icon', verse_id: '(Languages)'},
  {verse: 'heart on a laptop', verse_id: '(Online dating)'},
  {verse: "lightning above person's head", verse_id: '(Stress)'},
  {verse: '💡 with a brain inside', verse_id: '(Creativity)'},
  {verse: 'superman icon', verse_id: '(Heroes)'},
  {verse: 'smiling face', verse_id: '(Happiness)'},
  {verse: 'Google AdWords', verse_id: '(Marketing)'},
  {verse: '🌟 with name Tom Cruise', verse_id: '(Celebrities)'},
  {verse: 'Paper with 401k at the top', verse_id: '(Retirement)'},
  {verse: 'male and female symbols', verse_id: '(Stereotypes)'},
  {verse: '💰 dropped in hands', verse_id: '(Corruption)'},
  {verse: 'Cloud', verse_id: '(Weather)'},
  {verse: 'gold map', verse_id: '(The distant future)'},
  {verse: 'car', verse_id: '(Driving)'},
  {verse: 'tree near bench', verse_id: '(Parks / National Parks)'},
  {verse: 'rocketship', verse_id: '(Space)'},
  {verse: 'cat', verse_id: '(Animals)'},
  {verse: 'person with cane', verse_id: '(Aging)'},
  {verse: 'weight', verse_id: '(Exercise / Being active)'},
  {verse: 'beer', verse_id: '(Drinking)'},
  {verse: 'Google', verse_id: '(Googling)'},
  {verse: 'Tent', verse_id: '(Camping)'},
  {verse: 'Ice cream cone', verse_id: '(Ice cream)'},
  {verse: 'Dress', verse_id: '(Fashion)'},
  {verse: 'Four leaf clover', verse_id: '(Luck)'},
  {verse: 'Bed', verse_id: '(Sleep)'},
  {verse: 'Two wrenches', verse_id: '(Fixing things)'},
  {verse: 'canvas and paintbrush', verse_id: '(Art)'},
  {verse: 'Playing cards', verse_id: '(Cards)'},
  {verse: 'Tree', verse_id: '(Nature)'},
  {verse: 'Swimming', verse_id: '(Swimming)'},
  {verse: 'i icon', verse_id: '(Facts)'},
  {verse: 'thumbs down', verse_id: '(Pet peeves)'},
  {verse: 'Violin', verse_id: '(Musical instruments)'},
  {verse: 'History channel H', verse_id: '(History)'},
];
