topics = [
{verse: 'Worship the Lord your God and serve Him only.  Worship God in spirit and in truth.', verse_id: '-Lk 4.8 Mt 4.10 Jn 4.24'},
{verse: 'Do the will of him who sent me and accomplish his work.', verse_id: '-Jn 4.34'},
{verse: 'Repent and believe the Good News.', verse_id: '-Mt 4:17 Mk 1:15'},
{verse: 'Come and follow me.', verse_id: '-Mk 1.17'},
{verse: 'Be not afraid.', verse_id: '-Lk 5.10'},
{verse: 'Take heart ... your sins are forgiven.', verse_id: '-Mk 2.5 Mt 9.2'},
{verse: 'You ought to go learn what this means: "I desire mercy, not sacrifice."', verse_id: '-Mt 9.13'},
{verse: 'Call sinners to repentance.', verse_id: '-Lk 5.32'},
{verse: 'Do good on the Sabbath.', verse_id: '-Mk 3.5'},
{verse: '"Exercise justice amongst the nations." (Isa 42.2)', verse_id: '-Mt 12.18'},
{verse: 'Hunger and thirst after righteousness.', verse_id: '-Mt 5.6'},
{verse: 'Show mercy.', verse_id: '-Mt 5.7'},
{verse: 'Be glad ... and jump for joy.', verse_id: '-Mt 5.12 Lk 6.23'},
{verse: 'Let your light shine before others ... the good things you do.', verse_id: '-Mt 5.16'},
{verse: 'Make it right with him. Then return and offer your gift.', verse_id: '-Mt 5.24'},
{verse: 'Make peace and Try hard to reach a settlement.', verse_id: '-Mt 5.9 Mt 5.25 Lk 12.58'},
{verse: 'Cut it off and throw it away.', verse_id: '-Mt 5.30'},
{verse: 'Allow him to slap the other cheek also.', verse_id: '-Mt 5.39'},
{verse: 'Go two miles.', verse_id: '-Mt 5.41'},
{verse: 'Give to everyone who asks you for something.', verse_id: '-Mt 5.42 Lk 6.30'},
{verse: 'Love you enemies and treat well those who mistreat you, and bless those who curse you. Pray for those who abuse and persecute you.', verse_id: '-Mt 5.44 Lk 6.27'},
{verse: 'Love your enemies, do good to them and lend to them, looking for nothing in return.', verse_id: '-Lk 6.35'},
{verse: 'Be compassionate.... Be perfect.', verse_id: '-Mt 5.48 Lk 6.36'},
{verse: 'Give to the needy. Give to the needy in secret.  Pray. Pray to your Father in secret.  Fast. Fast ... in secret.', verse_id: '-Mt 6.2-6, 16-18'},
{verse: 'Pray like this....', verse_id: '-Mt 6.9'},
{verse: 'Forgive those who offend you.', verse_id: '-Mt 6.14'},
{verse: 'Observe the birds.  Observe how the lilies grow.', verse_id: '-Mt 6.26'},
{verse: 'First seek the kingdom of God and his righteousness.', verse_id: '-Mt 6.33 Lk 12.30'},
{verse: 'Remove the plank from you own eye.', verse_id: '-Mt 7.5'},
{verse: 'Ask ... seek ... knock.', verse_id: '-Mt 7.7'},
{verse: 'Treat other in the way you yourself would like to be treated.', verse_id: '-Mt 7.12'},
{verse: 'Do what I say.', verse_id: '-Mt 7.21'},
{verse: 'Do what my heavenly Father desires.', verse_id: '-Mt 7.21'},
{verse: 'Hear and obey me.', verse_id: '-Mt 7.24'},
{verse: 'Hear the Word of God and do it.', verse_id: '-Lk 8.21'},
{verse: 'Turn and be forgiven.', verse_id: '-Mt 4.12'},
{verse: 'Hear the Word with an honest and good heart. Welcome and understand it, grip it tightly, and patiently bear fruit.', verse_id: '-Mt 13.23 Lk 8.15 Mk 4.20'},
{verse: 'Go home to your relatives and tell them what great things the Lord God has done for you and how he had mercy on you.', verse_id: '-Mk 5.19'},
{verse: 'Come to me that you might have life.', verse_id: '-Jn 5.40'},
{verse: 'Pray to the Lord of the harvest that he will send out workers into his harvest fields.', verse_id: '-Mt 9.38'},
{verse: 'Go to the lost sheep....', verse_id: '-Mt 10.6'},
{verse: 'Say, "The kingdom of heaven has come."', verse_id: '-Mt 10.7'},
{verse: 'Heal the sick, raise the dead, cure the lepers, cast out demons.', verse_id: '-Mt 10.8'},
{verse: 'Freely you have received, freely give.', verse_id: '-Mt 10.8'},
{verse: 'When you enter a city or village, find out who is worthy.  Remain in whatever home you enter until you leave.  When you enter the home, say a greeting.  Allow your blessing to rest on it... return to you.  Shake off the dust from under your feet as a testimony.', verse_id: '-Mt 10.11-14'},
{verse: 'Be as wise as snakes and as gentle as doves.', verse_id: '-Mt 10.16'},
{verse: 'Do not fear them.', verse_id: '-Mt 10.26'},
{verse: 'Acknowledge me before others.', verse_id: '-Mt 10.32'},
{verse: 'Work ... for the lasting food that gives eternal life.', verse_id: '-Jn 6.27'},
{verse: 'Believe in the one whom he sent.', verse_id: '-Jn 6.29'},
{verse: 'Come to me ... believe in me ... believe in (the Son)', verse_id: '-Jn 6.35, 40, 47'},
{verse: 'Eat this bread ... eat my flesh ... eat his body ... eat my body ... drink his blood ... drink my blood.', verse_id: '-Jn 6.5, 53-54, 58'},
{verse: 'Watch out for the [teaching] of the Pharisees....', verse_id: '-Mk 8.15'},
{verse: 'Judge not by the looks of things; judge rightly.', verse_id: '-Jn 7.24'},
{verse: 'Go your way and stop sinning.', verse_id: '-Jn 8.11'},
{verse: 'Believe that I AM.', verse_id: '-Jn 8.24'},
{verse: 'Continue in my word ... be my disciples.', verse_id: '-Jn 8.31'},
{verse: 'Come after me ... own interests aside ... take up a cross ... and follow me.', verse_id: '-Mt 16.24 Mk 8.34'},
{verse: 'Believe in the Son of God.', verse_id: '-Jn 9.35'},
{verse: 'Believe the things I do.', verse_id: '-Jn 10.38'},
{verse: 'Have faith the size of a mustard seed.', verse_id: '-Mt 17.20'},
{verse: 'Be last of all and servant of all.', verse_id: '-Mk 9.35'},
{verse: 'Change your mind and become like little children.', verse_id: '-Mt 18.2'},
{verse: 'Humble yourselves.', verse_id: '-Mt 18.4'},
{verse: 'Listen carefully.', verse_id: '-Lk 9.44'},
{verse: 'Receive one such little child in my name.', verse_id: '-Mk 9.36'},
{verse: 'Go and tell him privately... Take one or two others with you... Tell it to the congregation... Treat him as you would a pagan or a tax collector.', verse_id: '-Mt 18.15-17'},
{verse: 'Bind ... release on earth.', verse_id: '-Mt 18.18'},
{verse: 'Gather in my name.', verse_id: '-Mt 18.20'},
{verse: '[Forgive a brother] up to seventy times seven.  Each of you, forgive your brother from your heart.', verse_id: '-Mt 18.22, Mt 18.35'},
{verse: 'Earnestly ask the Lord of the harvest to send out workers into his harvest.', verse_id: '-Lk 10.2'},
{verse: 'Heal the sick and say to them, "The kingdom of God has come hear."', verse_id: '-Lk 10.9'},
{verse: 'Rejoice that your names are recorded in heaven.', verse_id: '-Lk 10.20'},
{verse: 'Come to me, everyone who is weary and heavily laden.', verse_id: '-Mt 11.28'},
{verse: 'Put my yoke upon you and learn about me.', verse_id: '-Mt 11.29'},
{verse: 'Hear the Word of God and put it into practice.', verse_id: '-Lk 11.28'},
{verse: 'Ensure that your body is full of light.', verse_id: '-Lk 11.36'},
{verse: 'Give from the abundance of your heart.', verse_id: '-Lk 11.41'},
{verse: 'Fear the one who can both kill you and throw you into hell. Yes, be afraid of him.', verse_id: '-Lk 12.5'},
{verse: 'Acknowledge me before others.', verse_id: '-Lk 12.8'},
{verse: 'Watch out. Be on your guard against greed of all kinds.', verse_id: '-Lk 12.15'},
{verse: 'Be rich towards God.', verse_id: '-Lk 12.21'},
{verse: 'Sell your possessions and give to the poor. Provide money bags for yourselves that will not wear out.', verse_id: '-Lk 12.33'},
{verse: 'Be dressed and ready, and keep your lamps burning. Be like those who are waiting for their master....', verse_id: '-Lk 12.35'},
{verse: 'Be a servant that watches ... who is always ready.', verse_id: '-Lk 12.37-38'},
{verse: 'Be a trustworthy and wise manager.', verse_id: '-Mt 24.45'},
{verse: 'Produce much... contribute much.', verse_id: '-Lk 12.48'},
{verse: 'Try hard to enter through the narrow gate.', verse_id: '-Lk 13.24'},
{verse: 'Say, "Blessed is the one who comes in the name of the Lord."', verse_id: '-Lk 13.15'},
{verse: 'Take the least important place.', verse_id: '-Lk 14.9'},
{verse: 'Humble yourselves.', verse_id: '-Lk 14.11'},
{verse: 'Invite the poor....', verse_id: '-Lk 14.12'},
{verse: '"Hate" your (relatives).', verse_id: '-Lk 14.26'},
{verse: 'Take up your cross and follow Jesus.', verse_id: '-Lk 14.27'},
{verse: 'Sit down and calculate the cost.', verse_id: '-Lk 114.28'},
{verse: 'Leave everything you have... be my disciple.', verse_id: '-Lk 14.33'},
{verse: 'Leave the ninety-nine and search for the lost one.  Search carefully until (you) find it.', verse_id: '-Lk 15.4-8'},
{verse: 'Say... "I have sinned against God and you; I am no longer worthy...."', verse_id: '-Lk 15.18'},
{verse: 'Use worldly wealth to make friends for yourselves.', verse_id: '-Lk 16.9'},
{verse: 'Be faithful in the smallest things.', verse_id: '-Lk 16.10'},
{verse: 'Listen to Moses and the prophets.', verse_id: '-Lk 16.31'},
{verse: 'Say, "We are worthless servants who have only done our duty."', verse_id: '-Lk 17.10'},
{verse: 'Cry out to God day and night.', verse_id: '-Lk 18.7'},
{verse: 'Say, "God, be merciful to me, for I am a sinner."', verse_id: '-Lk 18.13'},
{verse: 'What God has united, let no one pull apart.', verse_id: '-Mk 19.9'},
{verse: 'Make (oneself) an unique for the Kingdom.  Whoever can accept celibacy, let him accept it.', verse_id: '-Mt 19.12'},
{verse: 'Believe in me.', verse_id: '-Jn 11.25-26, 40'},
{verse: 'Obey the commandments', verse_id: '-Mt 19.17'},
{verse: 'Leave house or parents or ... property.', verse_id: '-Mt 19.29 Mk 10.29 Lk 18,19'},
{verse: 'Go, work ... report to my vineyard.  Take your wages and go home.', verse_id: '-Mt 20.4, 7, 14'},
{verse: 'Drink the cup I drink.  Be baptized with the baptism I undergo.', verse_id: '-Mt 20.23'},
{verse: 'Become a servant ... the slave of all.', verse_id: '-Mt 20.27, 28 Mk 10.44'},
{verse: 'Serve ... give your life.', verse_id: '-Mt 20.28 Mk 10.45'},
{verse: 'Bring (blind men) to me.', verse_id: '-Mk 10.49'},
{verse: 'Recount what this woman has done.', verse_id: '-Mt 26.23 Mk 14.9'},
{verse: '"Call my house an house of prayer." (Isaiah 56:7)', verse_id: '-Lk 19.46'},
{verse: 'Praise from the mouths of babes and infants.', verse_id: '-Mt 21.16'},
{verse: 'Have faith.... Ask in prayer.... Truly believe.', verse_id: '-Mt 21.21, 22 Mk 11.24'},
{verse: 'Respect (the Son).  Produce (kingdom) fruit.  Read (the Scripture).', verse_id: '-Mt 21.38, 43, 42'},
{verse: 'Come to the wedding banquet.', verse_id: '-Mt 22.4'},
{verse: 'Invite to come anyone you find.', verse_id: '-Mt 22.9'},
{verse: "Give to Caesar what is Caesar's and to God what is God's.", verse_id: '-Mk 12.17 Lk 20.25'},
{verse: 'Understand the Scriptures (and) the power of God.', verse_id: '-Mt 22.29 Mk 12.24'},
{verse: '"Hear.... Love the Lord your God with all your heart, soul, mind and strength." (Deuteronomy 6.5)', verse_id: '-Mt 22.37 Mk 12.29-30'},
{verse: '"Love your neighbor as yourself." (Leviticus 19.18)', verse_id: '-Mt 22.39 Mk 12.30'},
{verse: '(Do) justice, mercy and faithfulness.', verse_id: '-Mt 23.23'},
{verse: 'First wash the inside of the cup and the disk.', verse_id: '-Mt 23.26'},
{verse: 'Hate your life in this world.', verse_id: '-Jn 12.25'},
{verse: 'Walk while you have the light.... Put your trust in the light while you have the light.', verse_id: '-Jn 12.25'},
{verse: 'Believe in me (and) the one who sent me.', verse_id: '-Jn 12.44, 46'},
{verse: 'Make sure you do not follow (deceivers).', verse_id: '-Lk 21.8'},
{verse: 'Testify before (authorities) and the Gentiles.  Say whatever is given to you at the moment.  Settle it in you heart not to ponder beforehand what to say.', verse_id: '-Mt 10.18 Lk 21.13'},
{verse: '(Show) patient endurance.', verse_id: '-Mt10.22 Mk 13.13 Lk 21.19'},
{verse: 'Endure to the end.', verse_id: '-Mt 24.13'},
{verse: 'Preach this good news of the kingdom to all the world as a testimony to all peoples.', verse_id: '-Mt 24.14 Mk 13.10'},
{verse: 'Pray (for an escape).', verse_id: '-Mt 24.19-20 Mk 13.17'},
{verse: 'Lift your heads and look up.', verse_id: '-Lk 21.28'},
{verse: 'Learn ... observe ... know that the Kingdom is drawing nigh.', verse_id: '-Mt 24.32-33 Mk 13.28-29 Lk 21.29-30'},
{verse: 'Watch yourselves.... Make sure your hearts.', verse_id: '-Lk 21.34'},
{verse: 'Watch and pray that you may have strength to escape.', verse_id: '-Lk 21.36'},
{verse: 'Be careful. Keep watch.... Watch.', verse_id: '-Lk 21.36, 25.13 Mk 13.35'},
{verse: 'Come ... inherit the Kingdom.', verse_id: '-Mt 25.34'},
{verse: "Give food ... give drink ... welcome ... clothe ... visit ... come to ... the least esteemed of (Jesus') brothers.", verse_id: '-Mt 25.35-36, 40'},
{verse: 'Call me teacher and Lord.', verse_id: '-Jn 13.13'},
{verse: "Wash each other's feet.", verse_id: '-Jn 13.15'},
{verse: 'Welcome whomever I send.... Welcome me.', verse_id: '-Jn 13.20'},
{verse: 'Believe me that I am in the Father and that the Father is in me.', verse_id: '-Jn 14.11'},
{verse: 'Believe me because of the miracles.', verse_id: '-Jn 14.11'},
{verse: 'Ask anything using my name.', verse_id: '-Jn 14.13, 14'},
{verse: 'Love me, keep my commandments', verse_id: '-Jn 14.15'},
{verse: 'Abide in me ... and I in you.', verse_id: '-Jn 15.5, 7'},
{verse: 'Continue in my love.', verse_id: '-Jn 15.9'},
{verse: 'Love me and believe that I came from God.', verse_id: '-Jn 16.27'},
{verse: 'Weep ... for yourselves and for your children.', verse_id: '-Lk 23.38'},
{verse: 'Believe everything the prophets spoke.', verse_id: '-Lk 24.25'},
{verse: 'Receive the Holy Spirit.', verse_id: '-Jn 20.22'},
{verse: 'Forgive ... sins.', verse_id: '-Jn 20.23'},
{verse: 'Love me more than these.', verse_id: '-Jn 21.15, 16, 17'},
{verse: 'Feed my lambs. Shepherd ... feed my sheep.', verse_id: '-Jn 21.15, 16, 18'},
{verse: 'Go and make disciples of all peoples, baptizing them in the name of the Father, of the Son, and of the Holy Spirit, and teaching them to obey all that I commanded.', verse_id: '-Mt 28.18-20'},
{verse: '[Go into the whole world and preach the good news to the whole creation.]', verse_id: '-Mk 16.15'},
{verse: '[Speak in tongues ... pick up snakes ... lay hands on the sick.]', verse_id: '-Mk 16.17-18'},
{verse: 'Proclaim repentance and forgiveness of sins, in my name to all nations.', verse_id: '-Lk 24.47'},
{verse: 'Relax until you are clothed with power from above.', verse_id: '-Lk 24.49.'},
{verse: 'Tell people about me everywhere.', verse_id: '-Ac 1.8'},
{verse: 'A wife must not leave her husband. A husband must not leave his wife.', verse_id: '-1 Co 6:10, 11'},
{verse: 'Look how far you have fallen from your first love. Turn back to me and do your first works.', verse_id: '-Ap 2.5'},
{verse: 'Remain faithful, even when facing death.', verse_id: '-Ap 2.10'},
{verse: 'Hold tightly to what you have until I come.', verse_id: '-Ap 2.25'},
{verse: 'Go back to what you heard and believed at first. Hold it firmly and urn to me again.', verse_id: '-Ap 3.3'},
{verse: 'Hold on to what you have.', verse_id: '-Ap 3.11'},
{verse: 'No Content', verse_id: ''}
];
